oas-heavy-small:
  source:
    type: csv
    path: ../tests/data/heavy_small/reference.csv

oas-light-small:
  source:
    type: csv
    path: ../tests/data/light_small/reference.csv

oas-light:
  source:
    postgres_db_connection_string_env: OAS_CONNECTION_STRING
    type: oas
