oas-heavy-small:
  groupings:
    1:
      - h_v
    2:
      - h_v
      - h_cdr3_len
  source:
    csv: /sim-seqer/tests/data/heavy_small/referece.csv

oas-light-small:
  groupings:
    1:
      - l_v
    2:
      - l_v
      - l_cdr3_len
  source:
    csv: /sim-seqer/tests/data/light_small/referece.csv

oas-light:
  groupings:
    1:
      - l_v
      - l_cdr3_len
  source:
    postgres_db_connection_string_env: OAS_CONNECTION_STRING
    get_group_query: /sim-seqer/bin/oas-l_cdr3_len.l_v.sql
    get_groups_query: /sim-seqer/bin/oas-l_cdr3_len.l_v.sql